export const ActionTypes = {
    GET_SCHOOLS :"GET_SCHOOLS",
    INDUIVAL_SCHOOLS : "INDUIVAL_SCHOOLS",
    LOGIN : "LOGIN",
    UPDATE_SCHOOL:"UPDATE_SCHOOL",
    DELETE_SCHOOL:"DELETE_SCHOOL",
    ADD_SCHOOL:"ADD_SCHOOL",
    SUGGESTION_LISTING:"SUGGESTION_LISTING",
    ADD_SUGGESTION:"ADD_SUGGESTION",
    SUGGESTION_ID :"SUGGESTION_ID"
}